# Generated by Django 5.0.4 on 2024-06-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=100, unique=True)),
                ('format', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='event',
            name='format',
        ),
        migrations.AddField(
            model_name='event',
            name='formats',
            field=models.ManyToManyField(related_name='events', to='events.format'),
        ),
    ]
