# Generated by Django 5.0.4 on 2024-10-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_city_alter_event_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='distance',
            field=models.CharField(max_length=100),
        ),
    ]
